server:
  port: 18080
  ssl:
    enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/palworldkorea?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kofiqa001
    password: jkb83n*#N

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

file:
  upload-dir: /mnt/ssd/palworldkorea/images/

